### ISSUE TITLE
Using flll in provider extension throws exception 

### ISSUE THREAD

**Issue by moe2k** [FluidTYPO3/flll#24]
In frontend, I get an exception when using flll (development or master) with my provider extension. I have whitelisted the key of my provider extension (con_myextension) to rule out any other influences. It also does not help to delete the default xlf file or any of the field names.

`#1: PHP Catchable Fatal Error: Argument 1 passed to TYPO3\CMS\Core\Utility\ArrayUtility::mergeRecursiveWithOverrule() must be of the type array, object given, called in /var/www/web/htdocs/development/typo3_src-6.2.13/typo3/sysext/frontend/Classes/Controller/TypoScriptFrontendController.php on line 4838 and defined in /var/www/web/htdocs/development/typo3_src-6.2.13/typo3/sysext/core/Classes/Utility/ArrayUtility.php line 517`

Stack trace:

`15 TYPO3\CMS\Core\Error\ErrorHandler::handleError(4096, "Argument 1 passed to TYPO3\CMS\Core\Utility\ArrayU…iptFrontendController.php on line 4838 and defined", "/var/www/web/htdocs/development/typo3_src-6.2.13/typo3/sysext/core/Classes/Utility/ArrayUtility.php", 517, array)`

`14 TYPO3\CMS\Core\Utility\ArrayUtility::mergeRecursiveWithOverrule(FluidTYPO3\Flll\LanguageFile\DynamicLabelAccessor, FluidTYPO3\Flll\LanguageFile\DynamicLabelAccessor, boolean, boolean)`

`13 TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController::readLLfile("EXT:con_myprovider/Resources/Private/Language/locallang.xlf")`

`12 TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController::sL("LLL:EXT:con_myprovider/Resources/Private/Language/locallang.xlf:flux.example.description")`

`11 TYPO3\CMS\Extbase\Utility\LocalizationUtility::translateFileReference("LLL:EXT:con_myprovider/Resources/Private/Language/locallang.xlf:flux.example.description")`

`10 TYPO3\CMS\Extbase\Utility\LocalizationUtility::translate("LLL:EXT:con_myprovider/Resources/Private/Language/locallang.xlf:flux.example.description", "con_myprovider")`

`9 FluidTYPO3\Flux\Form::getDescription()`

`8 FluidTYPO3\Fluidcontent\Service\ConfigurationService::buildWizardTabItem("Content", "Constructiva_ConMyprovider_Example_html", FluidTYPO3\Flux\Form, "Constructiva.ConMyprovider:Example.html")`

[...]

Caching is configured in the following way:
`$GLOBALS['TYPO3_CONF_VARS']['SYS']['caching']['cacheConfigurations']['cache_phpcode']['backend'] = 'TYPO3\CMS\Core\Cache\Backend\FileBackend';
$GLOBALS['TYPO3_CONF_VARS']['SYS']['caching']['cacheConfigurations']['extbase_object']['backend'] = 'TYPO3\\CMS\\Core\\Cache\\Backend\\FileBackend';
`

Extensions:
- TYPO3 6.2.14
- fluidpages 3.3.1
- flux 7.2.1
- fresh provider extension named "Constructiva.ConMyprovider" built via builder 0.20 (vendor/namespaced)

**Comment by moe2k** [comment]
Notice: It works (with flux fields in page templates) as soon as I remove the Example.html Content Template. So it seems to have to do with the specific flux field which is used in there.

**Comment by xf-** [comment]
confirmed in v7

**Comment by xf-** [comment]
This should help:
https://github.com/FluidTYPO3/flll/pull/26

**Comment by NamelessCoder** [comment]
Solved; the cache warmup that causes this issue no longer gets generated in an FE context - BE only.
